#lang planet neil/sicp
(define tolerance 0.00001)
(define (fixed-point f first-guess)
  (define (close-enough? v1 v2)
    (< (abs (- v1 v2)) tolerance))
  (define (try guess)
    (display guess)
    (newline)
    (let ((next (f guess)))
      (if (close-enough? guess next)
          next
          (try next))))
  (try first-guess))
(define (ex-36-transform a)
  (/ (log 1000) (log a)))
(define (ex-36-transform-avg-damping a)
  (average a (ex-36-transform a)))
(define (average a b)
  (/ (+ a b) 2))